---
apiVersion: v1
kind: Service
metadata:
  name: housepred
  namespace: default
  labels:
    app: housepred
spec:
  ports:
    - port: 80
  selector:
    app: housepred
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housepred
  namespace: default
  labels:
    app: housepred
spec:
  selector:
    matchLabels:
      app: housepred
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: housepred
        tier: frontend
    spec:
      containers:
      - image: danielmisik/udacity:ml-service
        name: housepred
        ports:
        - containerPort: 80
          name: housepred
