---
apiVersion: v1
kind: Service
metadata:
  name: housepred1
  namespace: default
  labels:
    app: housepred1
spec:
  ports:
    - port: 80
  selector:
    app: housepred1
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housepred1
  namespace: default
  labels:
    app: housepred1
spec:
  selector:
    matchLabels:
      app: housepred1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%  
  template:
    metadata:
      labels:
        build_number: v1
        app: housepred1
        tier: frontend
    spec:
      containers:
      - image: "{{ image_id }}"
        imagePullPolicy: "Always"
        name: housepred1
        ports:
        - containerPort: 80
          name: housepred1
