---
apiVersion: v1
kind: Service
metadata:
  name: housepred
  namespace: default
  labels:
    app: housepred
spec:
  ports:
    - port: 80
  selector:
    app: housepred
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housepred
  namespace: default
  labels:
    app: housepred
spec:
  selector:
    matchLabels:
      app: housepred
      role: rolling-update
  strategy:
    type: RollingUpdate
    rollingUp      maxSurge: 50%
  template:
    metadata:
      labels:
        build_number: v1
        app: housepred
        tier: frontend
        role: rolling-update
    spec:
      containers:
      - image: danielmisik/udacity:ml-service:latest
        imagePullPolicy: "Always"
        name: housepred
        ports:
        - containerPort: 80
          name: housepred
