---
apiVersion: v1
kind: Service
metadata:
  name: housepred
  namespace: default
  labels:
    app: housepred
spec:
  ports:
    - port: 80
  selector:
    app: housepred
    build: "{{ image_id }}"
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housepred
  namespace: default
  labels:
    app: housepred
spec:
  selector:
    matchLabels:
      app: housepred
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%  
  template:
    metadata:
      labels:
        app: housepred
        build: "{{ image_id }}"

    spec:
      containers:
      - image: "{{ image_id }}"
        imagePullPolicy: "Always"
        name: housepred
        ports:
        - containerPort: 80
          name: housepred
